name: Send Monthly Competition Emails

on:
  schedule:
    # Run on the 1st of every month at 9 AM UTC
    - cron: "0 9 1 * *"
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd src
          pip install -r ../requirements.txt

      - name: Send monthly emails
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FROM_NAME: ${{ secrets.FROM_NAME }}
          REPLY_TO: ${{ secrets.REPLY_TO }}
        run: |
          cd src
          python github_actions_email.py
